### ISSUE TITLE
Header and footer components are required lots of places

### ISSUE THREAD

**Issue by pietgeursen** [one-mile/client#11]
Prefer to have an App component that has the parts of the page that will always be there:
```js
function App(state, dispatch, child){
  return yo`
    <div id="app">
      ${header(state, dispatch)}
      ${child(state, dispatch)}
      ${footer(state, dispatch)}
    </div>
  `
}
```

And then you can just pass the particular view to the app component that you need.

**Comment by harrison-symes** [comment]
[Done](https://github.com/one-mile/client/commit/b9d3326535c28af31a162beb763f1f98c07d407a)
