### ISSUE TITLE
Add newly taken/uploaded image to state

### ISSUE THREAD

**Issue by kfrn** [one-mile/client#24]
Update code in reducer - construct new picture object and add it into the state. Not too tricky but too tired to finish tonight
Tackle with @ursula-f (or @mel-booth?) tomorrow morning. Should be pretty straightforward.

**Comment by harrison-symes** [comment]
I've just done this sorry, had camera issues on my end and wanted to resolve. the incomplete code is still on cloudinary branch if you want to compare it to what I did, happy to explain
